#print axioms model_centered_projective_ratio_bound
#print axioms model_centered_normalized_uniform_limit
#print axioms prime_three_centered_budget

end D5.S3.Weil.GroundMode.GenuineModelDualTransport
end
