            Describe.Lean(DescribeId.Create("diagonal_gamma_endpoint_error"),
                DeclarationHandle.Create("D5/S3/Weil/ZetaBridge/WeilDiagonalGammaRegularization.diagonal_gamma_endpoint_error"),
                H("Certified endpoint-strip budget"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For any delta in [0,L], the absolute integral over (0,delta] is bounded by delta times the explicit regularized majorant. This enables a justified finite evaluator to retain the singular endpoint contribution. It supplies neither an interior evaluator nor a new actual prolate error certificate."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("diagonalGammaSeriesTerm"),
                DeclarationHandle.Create("D5/S3/Weil/ZetaBridge/WeilDiagonalGammaRegularization.diagonalGammaSeriesTerm"),
                H("Finite elementary relative-diagonal term"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The explicit term is the original positive Gamma resolvent contribution minus the finite-window correction. Its parameters are L, the integer Fourier index n, and the Gamma index j. It contains only real arithmetic and exp, without an infinite sum or integral. It is not an extracted, verified rational transcendental evaluator."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("diagonal_gamma_hasSum"),
                DeclarationHandle.Create("D5/S3/Weil/ZetaBridge/WeilDiagonalGammaRegularization.diagonal_gamma_hasSum"),
                H("Complete nonnegative diagonal series"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("An explicit triangular exponential-cosine primitive evaluates each term. The already-owned exponential kernel expansion, an integrable majorant and dominated convergence identify the entire sum with the difference of the two original regularized diagonal integrals. Nonnegative terms, absolute summability and all endpoint terms are derived."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("diagonal_gamma_series_error"),
                DeclarationHandle.Create("D5/S3/Weil/ZetaBridge/WeilDiagonalGammaRegularization.diagonal_gamma_series_error"),
                H("All omitted terms have an inverse-square budget"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Keeping Gamma indices zero through K inclusive yields a lower partial sum and an upper sum plus 2*(2*pi*n/L)^2/(4*K+3)^2. The positive inverse-cube term majorant is summed by an explicit telescope. The complete tail is retained, with K=0 and both signs of n allowed."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("diagonal_gamma_resolvent_window_bounds"),
                DeclarationHandle.Create("D5/S3/Weil/ZetaBridge/WeilDiagonalGammaRegularization.diagonal_gamma_resolvent_window_bounds"),
                H("Uniform finite-window correction"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The finite positive resolvent sum G obeys G-39/(4*L)<=E and E<=G+2*(2*pi*n/L)^2/(4*K+3)^2. The correction bound is uniform in the Fourier index. It follows from the explicit rational maximum 9/4 and the reciprocal-square prefix bound 13/3. This scalar diagonal fact does not imply full-matrix coercivity or control arbitrary cross terms."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("diagonal_gamma_finite_enclosure"),
                DeclarationHandle.Create("D5/S3/Weil/ZetaBridge/WeilDiagonalGammaRegularization.diagonal_gamma_finite_enclosure"),
                H("Finite rational certificate for the original diagonal difference"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Justified rational balls for the finite explicit terms and a rational absolute-frequency bound produce rational endpoints for the original integral difference. All term errors and all omitted Gamma terms enter the result. This is a small consumer of the analytic series theorem, not a new verified log, pi or exp implementation."))), DescribeRole.Theorem)),
        [DocumentEdge.Dependency.Create(GidRef.Create("D5/S3/Weil/ZetaBridge/WeilWindowFourierConvolution"))]));
}
