using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Weil.BurnolGram;

internal sealed class FiniteBoxWeilMollifierDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S3/Weil/BurnolGram/FiniteBoxWeilMollifier.";
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite box convolution constructs actual even smooth compact seeds with unit mass and explicit finite-order L1 derivative bounds, eliminating dependence on unknown initial bump derivatives.",
        H("Finite Box Smoothing and Quantitative Weil Seeds"),
        Blocks(
            Describe.Lean(DescribeId.Create("finite-box-density"),
                DeclarationHandle.Create(Prefix + "boxDensity"), H("The normalized box density"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The density is an integrable raw function, not itself a smooth Weil test. Unit mass and unit L1 norm require a>0."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-box-mean"),
                DeclarationHandle.Create(Prefix + "boxMean"), H("Actual smooth box averaging"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Mathlib convolution regularity gives smoothness from the compact smooth right input. Symmetry of the interval preserves evenness."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-box-integral"),
                DeclarationHandle.Create(Prefix + "boxMean_integral"), H("The integral is preserved"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Apply the actual convolution integral identity and the computed unit box mass."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-l1-contraction"),
                DeclarationHandle.Create(Prefix + "boxMean_norm_integral_le"), H("L1 contraction"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The integral triangle inequality and the integral of the scalar convolution give Young's L1 inequality with unit constant."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-support"),
                DeclarationHandle.Create(Prefix + "boxMean_tsupport"), H("Additive support cost"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Use the existing convolution-support containment and closedness of the enclosing interval."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-derivative-difference"),
                DeclarationHandle.Create(Prefix + "boxMean_iterate_deriv_succ"), H("One derivative consumes one box"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Convolution differentiation moves derivatives to the smooth input. The ordinary fundamental theorem of calculus evaluates the final box integral. Literature anchor: Michele Vergne, A remark on the convolution with the box spline, Annals of Mathematics 174 (2011), 607-618, Section 1, the derivative/difference identity immediately preceding Section 2; DOI 10.4007/annals.2011.174.1.19. The present result is the centered one-dimensional scaled specialization."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-iterate"),
                DeclarationHandle.Create(Prefix + "boxIterate"), H("Finite iteration"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The zero iteration retains the existing smooth seed. No distributional identity is installed as a Weil test."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-box-iterate-mass"),
                DeclarationHandle.Create(Prefix + "boxIterate_integral"), H("Unit mass at every finite depth"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Induct on q using mass preservation of one box average."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-iterate-jet"),
                DeclarationHandle.Create(Prefix + "boxIterate_derivative_L1_budget"), H("Finite jets without initial jet assumptions"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Induction charges each derivative to a different box. Translation invariance bounds the centered difference by a^(-1) times the previous L1 norm. No derivative seminorm of g is used."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-iterate-support"),
                DeclarationHandle.Create(Prefix + "boxIterate_tsupport"), H("Finite support accumulation"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("Induct on the existing support containment."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-width"),
                DeclarationHandle.Create(Prefix + "finiteBoxWidth"), H("Explicit box width"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The denominator is positive for h>0, including q=0."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-box-seed"),
                DeclarationHandle.Create(Prefix + "finiteBoxSeed"), H("The actual derivative-controlled seed"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(), Blocks(Paragraph(Text("The canonical smooth bump contributes unit mass. Its uncomputed high derivatives never enter the budget."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("finite-box-seed-budget"),
                DeclarationHandle.Create(Prefix + "finiteBoxSeed_budget"), H("Constructed simultaneous quantitative budget"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The support is bounded by h/2+qh/(2(q+1))<=h. L1 contraction and the unit integral force L1=1. The derivative inequality is the finite-box estimate specialized to this explicit width."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("finite-box-seed-transform-floor"),
                DeclarationHandle.Create(Prefix + "finiteBoxSeed_transform_lower"), H("A common explicit transform denominator floor"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Reuse the proved compact-support transform perturbation bound and unit mass/L1. This combines support, a finite derivative budget and nonvanishing for actual functions. Source is Candidate; no pinned Lean compilation is claimed."))), DescribeRole.Theorem)), []));
}
