using static StrataLint.Scribe.DefinitionDsl;
using static StrataLint.Scribe.FormulaDsl;
using F = StrataLint.Scribe.FormulaDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Weil.BurnolGram;

internal sealed class WeilMixedHeadTailBudgetDocument : IScribeDocumentDefinition
{
    private const string Prefix = "D5/S3/Weil/BurnolGram/WeilMixedHeadTailBudget.";
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Finite transform enclosures and a scalar fourth-moment tail control the actual full mixed-majorant constant without assuming a bound on that operator-family constant.",
        H("Finite Head and Fourth-Moment Tail Budget"),
        Blocks(
            Describe.Lean(DescribeId.Create("weil-mixed-jet-closed-strip-jet-budget-le-three-jets"),
                DeclarationHandle.Create(Prefix + "closedStripJetBudget_le_three_jets"),
                H("Rational two-jet decay coefficient"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The weighted integrals are bounded using support and exp(1/2)<3. Both L1 bounds refer to the actual test and its actual second derivative."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-mixed-jet-zero-transform-pair-le-three-jets"),
                DeclarationHandle.Create(Prefix + "zero_transform_pair_le_three_jets"),
                H("Two conjugate readings from finite jets"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The critical strip bound is unconditional. Apply the named closed-strip budget at gamma_n and its conjugate; both have the same real ordinate."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weil-mixed-jet-finite-mixed-majorant-total-le-unit-support-jets"),
                DeclarationHandle.Create(Prefix + "finiteMixedMajorantTotal_le_unit_support_jets"),
                H("No assumed transform-decay constant remains"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Combine the derived two-sided transform estimate with the full mixed head-tail theorem. The scalar zero-tail bound remains the explicitly identified number-theoretic input; the published BPT estimate has not been kernel-ported here."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-inverse-quadratic-envelope"),
                DeclarationHandle.Create(Prefix + "inverseQuadraticEnvelope"),
                H("Ordinate decay envelope"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The real part of gamma is the actual zero ordinate. The strip displacement is not used as the ordinate."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-fourth-moment-summand"),
                DeclarationHandle.Create(Prefix + "fourthMomentSummand"),
                H("Multiplicity-weighted scalar tail"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Exactly one analytic multiplicity factor is present per zero index."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-finite-mixed-head-bound"),
                DeclarationHandle.Create(Prefix + "finiteMixedHeadBound"),
                H("A finite enclosure expression"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The data bound both conjugate evaluations of each actual test. The expression includes every off-diagonal mixed term."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-finite-mixed-majorant-head-le"),
                DeclarationHandle.Create(Prefix + "finiteMixedMajorant_head_le"),
                H("Finite mixed head enclosure"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Expand the actual mixed summand, multiply nonnegative norm bounds, and factor the two finite coefficient sums."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-finite-mixed-majorant-pointwise-decay"),
                DeclarationHandle.Create(Prefix + "finiteMixedMajorant_pointwise_decay"),
                H("All tail cross terms at once"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Use the existing exact polarized Fourier-Laplace factorization. Multiplicity is counted once and no cross terms are dropped."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-finite-mixed-majorant-total-le-head-tail"),
                DeclarationHandle.Create(Prefix + "finiteMixedMajorantTotal_le_head_tail"),
                H("Derived complete majorant bound"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Split the actual absolutely convergent mixed sum into E and its complement, compare the latter to the positive scalar tail, and sum. A bound on C_actual is a conclusion, not a field of a certificate. Brent-Platt-Trudgian (2021), Theorem 1, equations (1)-(3), is the literature entry for the remaining scalar tail; its numerical zeta-count estimates are not automatically imported by this theorem."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("weilmixedheadtailbudget-fourth-moment-summand-le-inverse-fourth"),
                DeclarationHandle.Create(Prefix + "fourthMomentSummand_le_inverse_fourth"),
                H("Interface to the published inverse-power sum"),
                StatementSource.WithoutFormula(),
                AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("This supplies the envelope comparison for an inverse-fourth tail. Positive-height versus two-sided sums and endpoint half weights must still be reconciled in an application."))), DescribeRole.Theorem)), []));
}
