#!/usr/bin/env python3
"""op-body-facts.py WORKTREE [READINGS_MD] — emit the head-bound factual section of a deposit PR body.

Two review seats rejected two different PRs this session for the same defect: the body's "current"
section described a superseded head after the deposit was rebuilt. Every fact below is read from what
the rebuild actually produced — the accepted Freeze event, the frozen state pin, the coverage edges,
the changed-path set and the module source — so the section cannot drift from the head again.

The declaration account is deliberately three-layered, because a single "public" number is ambiguous:
the Freeze event records every constant the module elaborates, including Lean-generated auxiliaries,
private declarations, constructors, recursors and structure projections. Only the authored top-level
non-private declarations are what a review seat means by the public surface, and the projections are
listed separately rather than silently folded into either number.
"""
import json, os, re, subprocess, sys, pathlib

GEN = re.compile(
    r'\.(eq_def|eq_\d+|match_\d+(_\d+)*|proof_\d+(_\d+)*|sizeOf_spec|_sizeOf_inst|_sizeOf_\d+|_f|_sunfold'
    r'|_unsafe_rec|_mutual|injEq|inj|noConfusion\w*|noConfusionType|rec|recOn|casesOn|mk\.\w+|below|brecOn'
    r'|ibelow|binductionOn|ctorIdx|_flat_ctor)$|\._sizeOf')
# A review seat caught this parse missing `@[simp] theorem formula_append_zero_zero`, which the
# classifier below then reported as an autogenerated projection. Attributes may precede the
# keyword on the same line or on their own lines, and `protected`/`private` may sit between.
AUTHORED = re.compile(
    r'^(?!\s*private\b)(?:@\[[^\]]*\]\s*)*(?:protected\s+)?(?:noncomputable\s+)?'
    r'(theorem|lemma|def|abbrev|instance|structure|inductive|class)\s+'
    r'([A-Za-z_][\w\'.]*)', re.M)


SELFTEST_CASES = [
    # (source line, expected parsed name or None) — positives first, then negative controls.
    ("theorem plain_one : True := trivial", "plain_one"),
    ("@[simp] theorem attributed : True := trivial", "attributed"),
    ("@[simp, norm_cast] theorem two_attributes : True := trivial", "two_attributes"),
    ("protected theorem protected_one : True := trivial", "protected_one"),
    ("@[simp] protected theorem attributed_protected : True := trivial", "attributed_protected"),
    ("noncomputable def ncdef : Nat := 0", "ncdef"),
    ("structure Pair where", "Pair"),
    ("private theorem hidden : True := trivial", None),
    ("private def hidden_def : Nat := 0", None),
    ("  theorem indented_is_not_top_level : True := trivial", None),
    ("example : True := trivial", None),
]


def selftest() -> int:
    """Pin the authored-declaration parser against the cases that actually went wrong.

    On 2026-09-08 this regex required the keyword at line start, so `@[simp] theorem
    formula_append_zero_zero` never matched and the classifier reported a hand-written theorem as an
    autogenerated projection. Three review seats caught it. The same regex, copied into the sibling
    shapes tool, then dropped that declaration from its table too. These cases are the regression pin.
    """
    failures = []
    for line, expected in SELFTEST_CASES:
        got = [m.group(2) for m in AUTHORED.finditer(line)]
        actual = got[0] if got else None
        if actual != expected:
            failures.append(f"{line!r} expected {expected!r} got {actual!r}")
    for f in failures:
        print("FAIL", f)
    print(f"SELFTEST cases={len(SELFTEST_CASES)} failures={len(failures)}")
    return 1 if failures else 0


def git(w, *a):
    return subprocess.run(["git", "-C", w, *a], capture_output=True, text=True).stdout.strip()


def decl_name(key: str, module_comps: list[str]) -> str:
    comps = re.findall(r'\d+:([^)]+)\)', key)
    if comps[:len(module_comps)] == module_comps:
        return '.'.join(comps[len(module_comps):])
    return '.'.join(comps) if comps else key


def main(worktree: str, readings: str | None) -> int:
    w = worktree
    head = git(w, "rev-parse", "HEAD")
    branch = git(w, "rev-parse", "--abbrev-ref", "HEAD")
    # Label this precisely: it is the merge base of the head with the local origin/dev ref at generation
    # time, not the current remote dev head. A seat rejected an earlier body for calling it "current dev";
    # the remote moves every few minutes and the two are routinely different SHAs.
    base = git(w, "merge-base", "HEAD", "origin/dev")
    changed = [p for p in git(w, "diff", "--name-only", "origin/dev...HEAD").splitlines() if p]
    events = [p for p in changed if p.startswith("Golden/Frozen/accepted/")]
    states = [p for p in changed if p.startswith("Golden/Frozen/state/")]
    cover = [p for p in changed if p.startswith("Meta/Digestion/backfill/")]
    if len(events) != 1:
        print(f"BODY_FACTS_FAIL expected exactly one accepted event, found {len(events)}", file=sys.stderr)
        return 3

    ev = json.load(open(os.path.join(w, events[0])))
    p = ev.get("payload", ev)
    module_path = p.get("descriptor_selector", "")
    module_comps = module_path[:-5].split("/") if module_path.endswith(".lean") else []
    decls = [(decl_name(d.get("declaration_name_key", ""), module_comps), d.get("kind", ""),
              d.get("statement_id", "")) for d in (p.get("declaration_statement_ids") or [])]

    src = pathlib.Path(os.path.join(w, module_path)).read_text(encoding="utf-8") if module_path else ""
    authored_names = [m.group(2) for m in AUTHORED.finditer(src)]

    surviving = [t for t in decls if not GEN.search(t[0]) and "_private." not in t[0]
                 and t[1] not in ("constructor", "recursor")]
    aset = set(authored_names)
    def is_authored(n: str) -> bool:
        return n in aset
    authored = [t for t in surviving if is_authored(t[0])]
    # Anything the source parse did not match is UNCLASSIFIED, never silently called a projection:
    # a parse gap and an autogenerated declaration are different facts and must not print alike.
    unmatched = [t for t in surviving if not is_authored(t[0])]
    missing = [n for n in authored_names if n not in {t[0] for t in surviving}]

    prereq = p.get("prerequisite_frozen_node_ids") or []
    prereq_list = list(prereq.keys()) if isinstance(prereq, dict) else list(prereq)

    state_pin = None
    if states:
        try:
            state_pin = (json.load(open(os.path.join(w, states[0]))) or {}).get("statement_id")
        except Exception:
            state_pin = None

    edges = []
    for c in cover:
        try:
            import yaml  # type: ignore
            y = yaml.safe_load(open(os.path.join(w, c)).read()) or {}
            for g in (y.get("coverage_gids") or []):
                edges.append((os.path.basename(c)[:-5], g.get("gid")))
        except Exception:
            pass

    print("## 当前 head 的读数(由 `op-body-facts.py` 从本次重做实际产出的工件生成)\n")
    print(f"- **head**:`{head}`(分支 `{branch}`)。")
    print(f"- **合并基**:`{base[:10]}` —— 这是本 head 与生成时本地 `origin/dev` 引用的 merge-base,"
          f"**不是远端 dev 的当前 head**(远端每几分钟前进一次,两者通常不同)。")
    print(f"- **改动面**:{len(changed)} 个路径 —— {len(events)} 个 accepted 事件、{len(states)} 个状态片、"
          f"{len(cover)} 个消化账目条目,其余为模块、Scribe 及其投影。")
    print(f"- **Freeze 事件**:`{os.path.basename(events[0])[:-5]}`,`event_type={ev.get('event_type')}`,"
          f"`schema_version={ev.get('schema_version')}`。")
    print(f"- **模块 statement_id**:`{p.get('statement_id')}`"
          + (f";状态片 pin `{state_pin}`,与事件一致:{state_pin == p.get('statement_id')}。" if state_pin else "。"))
    print(f"- **直接冻结前置(`prerequisite_frozen_node_ids`)**:"
          + ("无。" if not prereq_list else ", ".join(f"`{x}`" for x in prereq_list) + "。"))
    if edges:
        print("- **覆盖边**:" + "; ".join(f"atom `{a[:12]}…` → `{g}`" for a, g in edges) + "。")
    print(f"\n### 声明账(三层,一处真源)\n")
    # Say only what the event actually records. A review seat caught the earlier wording, which claimed
    # these were every constant the module elaborates; the event records the declarations it pins, and
    # the elaborated environment contains more than that.
    print(f"- 该 Freeze 事件的 `declaration_statement_ids` 共 **{len(decls)}** 条"
          f"(事件所钉的声明,不等于模块 elaborate 出的全部常量)。")
    print(f"- 去掉 Lean 生成的辅助声明、`_private.` 私有声明、构造子与 recursor 后剩 **{len(surviving)}** 个。")
    print(f"- 其中**源码自写的顶层非 private 声明 {len(authored)} 个**(即评审席所指的公开面),"
          f"另 **{len(unmatched)} 个**未被源码解析命中——**这不是「自动产生」的判词**,只是解析没匹配上,逐条列在下面须人工归类。")
    if missing:
        print(f"- **差集非空(须查明)**:源码声明了但事件中没有 —— {', '.join('`'+m+'`' for m in missing)}。")
    else:
        print(f"- 源码声明与事件的差集为空。")
    print(f"\n### 源码自写的公开声明(名、kind、statement_id 全取自上面那个 Freeze 事件)\n")
    print("| 公开声明 | kind | statement_id |")
    print("|---|---|---|")
    for name, kind, sid in authored:
        print(f"| `{name}` | {kind} | `{sid}` |")
    if unmatched:
        print(f"\n<details><summary>未被源码解析命中的 {len(unmatched)} 个(须人工归类:结构投影?属性前缀?)</summary>\n")
        print("| 声明 | kind | statement_id |")
        print("|---|---|---|")
        for name, kind, sid in unmatched:
            print(f"| `{name}` | {kind} | `{sid}` |")
        print("\n</details>")
    if readings and pathlib.Path(readings).exists():
        print(f"\n### 门读数(逐门退出码,本次重做脚本记录)\n")
        print(pathlib.Path(readings).read_text().rstrip())
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None))
