using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.StatisticalMechanics.HardCore.Holomorphic;

internal sealed class AdaptiveComplexNeighborhoodDocument : IScribeDocumentDefinition
{
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Explicit holomorphic hard-core coordinates and uniform complex neighborhoods.",
        H("AdaptiveComplexNeighborhood"),
        Blocks(
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-actual-coefficient-bounds"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.actual_coefficient_bounds"),
                H("actual coefficient bounds"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The analytic estimate uses this additional exact bound on the same payload. The lower bound and slope sign are reused from the existing full-box certificate."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-Pruning"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.Pruning"),
                H("Pruning"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("A subset of actual geometric children. The root is separately treated."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-childType"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.childType"),
                H("childType"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Total accessor, used only on genuine children by Pruning."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-Omega"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.Omega"),
                H("Omega"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Explicit open tube around each actual type's compact real chart image."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-ActivityTube"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.ActivityTube"),
                H("ActivityTube"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("One open activity neighborhood, independent of graph size and recursion depth."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-adaptiveMap"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.adaptiveMap"),
                H("adaptiveMap"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual transformed map for the supplied geometric parent and child subset."))), DescribeRole.Definition),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-neighborhoods-open"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.neighborhoods_open"),
                H("neighborhoods open"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The constructed message and activity domains really are open."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-adaptive-uniform-invariant"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.adaptive_uniform_invariant"),
                H("adaptive uniform invariant"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Every actual type and every allowed pruning has the same invariant complex neighborhood. Its widths are explicit: delta=10^-20, epsilon=10^-30. No existence, Lipschitz, holomorphy or complex-invariance premise is supplied."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-omega-chart-inverse"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.omega_chart_inverse"),
                H("omega chart inverse"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The principal logarithm is the true inverse throughout each constructed message neighborhood. Imaginary phase wrapping is excluded by the actual width."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-adaptive-holomorphic-recovery"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.adaptive_holomorphic_recovery"),
                H("adaptive holomorphic recovery"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("On the constructed neighborhood, the map is jointly holomorphic and its inverse coordinate is exactly the hard-core vacancy, with both poles excluded."))), DescribeRole.Theorem),
            Describe.Lean(DescribeId.Create("hc-holo-adaptivecomplexneighborhood-four-child-root-nonzero"),
                DeclarationHandle.Create("D5/S3/StatisticalMechanics/HardCore/Holomorphic/AdaptiveComplexNeighborhood.four_child_root_nonzero"),
                H("four child root nonzero"), StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Four root factors need nonvanishing, not a three-child contraction claim. Every first child may use the already-owned initial type zero."))), DescribeRole.Theorem))));
}
