using static StrataLint.Scribe.DefinitionDsl;

namespace StrataLint.Scribe.Blueprint.D5.S3.Weil.GroundMode;

internal sealed class GenuineModelDualTransportDocument : IScribeDocumentDefinition
{
    private const string Owner = "D5/S3/Weil/GroundMode/GenuineModelDualTransport.";
    public DocumentDefinition Create() => DocumentDefinition.Create(ScribeNode.Create(
        "Candidate domain-level proofs; Lean elaboration and Scribe emission have not been run.",
        H("Genuine Model Dual Transport"),
        Blocks(
            Describe.Lean(
                DescribeId.Create("genuine-model-candidate-overlap-floor"),
                DeclarationHandle.Create(Owner + "candidate_overlap_floor"),
                H("The actual overlap is bounded away from zero"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Cauchy-Schwarz against the unit candidate and the reverse triangle inequality give 1-epsilon<=|<k,e>|. This is the denominator used by the hyperplane elimination, not a sampled angle."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-near-candidate-complement-coercivity"),
                DeclarationHandle.Create(Owner + "near_candidate_complement_coercivity"),
                H("Transfer coercivity to the genuine model"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For f orthogonal to e, subtract beta e with beta=<k,f>/<k,e> to obtain a k-orthogonal domain vector. Retain the exact norm and energy identities and the full model residual r=Ae-mu e. The resulting threshold is T-2*rho*epsilon/(1-epsilon), derived without assuming coercivity on e-perp. The actual model belongs to the operator domain; L2 proximity alone is insufficient."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-recentered-trial-residual-identity"),
                DeclarationHandle.Create(Owner + "recentered_trial_residual_identity"),
                H("Retain the infinite-support correction"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The trial v-<e,v>e stays in the actual linear domain and is e-orthogonal. Its full projected residual equals P_e(g-Mv+<e,v>*(Me-nu e)). No finite-support tail theorem is applied to this generally infinite-support repaired trial."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-recentered-trial-residual-bound"),
                DeclarationHandle.Create(Owner + "recentered_trial_residual_bound"),
                H("A complete transported residual budget"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Use contraction of the e-complement projection, the old complete projected residual, the old raw residual component along k, and the same full model residual. Every term produced by moving the candidate direction is paid for."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-recentered-trial-objective-bound"),
                DeclarationHandle.Create(Owner + "recentered_trial_objective_bound"),
                H("Preserve the signed variational objective"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Expand the actual symmetric domain energy after repair. Both complex mixed terms are retained. The signed objective is not reclassified as a norm, and the model residual controls its unbounded-action contribution."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-recentered-dual-coefficient-bound"),
                DeclarationHandle.Create(Owner + "recentered_dual_coefficient_bound"),
                H("Consume in the existing energy-dual theorem"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The left expression is exactly the coefficient already consumed by CoerciveDualCertificate and ProjectiveEnergyDual in PR #5882. Independently certified finite-trial caps and the full genuine-model residual give its explicit upper bound. The new real prolate consumer uses the same fixed-window model certified in #5602; the numerical transport is not a new eigenvalue enclosure or an all-scale rate."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-positive-form-complement-coercivity"),
                DeclarationHandle.Create(Owner + "positive_form_complement_coercivity"),
                H("A positive shifted form controls the moving complement"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Use the independent whole-domain lower certificate for M=A-ell. Positivity at t*f+alpha*k derives the energy Young inequality. Orthogonal projection onto k-perp and the geometric distance to e give kappa*(1-epsilon^2)/(1+t)-delta*epsilon^2/t as a new coercivity bound. No norm of M(e), Rayleigh residual or graph-distance assumption occurs. The shifted positivity premise is additional to the earlier residual-based route and cannot be omitted."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-positive-form-readout-transport"),
                DeclarationHandle.Create(Owner + "positive_form_readout_transport"),
                H("Transport the existing directional inequality directly"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Consume the old full-residual energy-dual readout bound on k-perp. Decompose the same test vector into its old perpendicular and candidate components, retaining the old-candidate readout G. The positive-form comparison and derived new coercivity give an explicit coefficient on e-perp. This is inequality transport, not a claim that a repaired infinite-support trial has zero residual. The original full-residual certificate remains the input provider for C."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-positive-form-uniform-readout-bound"),
                DeclarationHandle.Create(Owner + "positive_form_uniform_readout_bound"),
                H("A quadratic relative-angle criterion for changing scales"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Choosing both balancing parameters equal to one proves a retained gap kappa/4 and coefficient 8*C+8*epsilon^2*G^2/kappa when epsilon^2*(kappa/2+delta)<=kappa/4. These uniform formulas contain no genuine-model graph residual. For a scale family, weighted C tending to zero and weighted epsilon^2*G^2/kappa tending to zero suffice for this readout bound to vanish, subject to the independently verified hypotheses. The actual arithmetic scale rates are not supplied by this theorem."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-prime-three-positive-form-budget"),
                DeclarationHandle.Create(Owner + "prime_three_positive_form_budget"),
                H("Exact arithmetic for the existing prime-three inputs"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("With the unchanged global lower bound, finite-candidate energy ceiling, genuine-model distance and old full-residual coefficient cap, the rational t=1/100000 and s=1/10000 retain more than 99997/100000 of the shifted gap and give coefficient below 5151/50. The stated true-model energy width then gives Fourier error below 681/1000000. This theorem checks implications between rational constants only. It does not regenerate or independently prove the inherited spectral, form-domain, Fourier or model certificates."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-prime-three-centered-budget"),
                DeclarationHandle.Create(Owner + "prime_three_centered_budget"),
                H("Exact rational centered-certificate arithmetic"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("From the archived energy values, the two rational balancing parameters and C<108, exact arithmetic proves the anchor and normalized-error guards. The model-origin floor, log(3)<11/10 and complete centered residual cap remain independent analytic or interval inputs. This does not claim a new spectral enclosure."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-centered-readout-identity"),
                DeclarationHandle.Create(Owner + "model_centered_readout_identity"),
                H("Center the actual normalized observable"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The Riesz vector g-conj(<g,e>/<g0,e>)*g0 annihilates the same genuine model. The exact quotient identity and required conjugation are proved before any estimate. The anchor and actual denominator remain nonzero in this algebraic lemma."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-annihilating-energy-dual-transport"),
                DeclarationHandle.Create(Owner + "annihilating_energy_dual_transport"),
                H("Preserve annihilation during the hyperplane change"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Use beta=<k,f>/<k,e> to eliminate the old candidate direction. Since the centered readout annihilates e, its value is unchanged. Positive-form energy Young and the independently justified new-complement gap give a multiplicative coefficient. No additive old candidate-readout term is present. The old dual coefficient must certify this centered Riesz vector, not the uncentered g."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-positive-form-centered-readout-bound"),
                DeclarationHandle.Create(Owner + "positive_form_centered_readout_bound"),
                H("Derive a uniform four-times centered coefficient"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The already-owned positive shifted-form theorem derives the kappa/4 new gap from the original relative-angle condition. When epsilon<=1/2 and model energy<=kappa/4, the centered coefficient is at most 4C. The whole-domain shifted positivity and the centered old dual certificate remain essential."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-centered-projective-ratio-bound"),
                DeclarationHandle.Create(Owner + "model_centered_projective_ratio_bound"),
                H("Actual eigenvector ratio with a derived anchor"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Use the existing projective Rayleigh enclosure and energy identity to derive q(w)<=nu. The squared origin-kernel margin yields a nonzero denominator for the actual eigenvector; its phase and scale cancel in the quotient. Combine this with the multiplicative centered estimate. The conclusion compares the actual eigenvector and the same genuine model."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-centered-normalized-uniform-limit"),
                DeclarationHandle.Create(Owner + "model_centered_normalized_uniform_limit"),
                H("A single centered directional rate on moving domains"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The target set, operators, domains, eigenvectors and readouts may vary with scale. The derived anchor and four-times centered coefficient reduce normalized uniform error to nu*C/b^2 tending to zero. This is not a proof of that arithmetic rate for the actual unbounded Weil/prolate family. The generic readout can use the already-identified Fourier Riesz vector; no new Fourier definition or interval-oracle theorem is introduced."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-repair-preserves-residual-pairing"),
                DeclarationHandle.Create(Owner + "model_repair_preserves_residual_pairing"),
                H("The repaired trial keeps the signed model defect"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Symmetry derives the real Rayleigh pairing. Its full residual is orthogonal to the unit model, so subtracting any multiple of that model leaves the signed pairing unchanged. The original trial action and the complete model still occur; no finite truncation is asserted."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-centered-goal-residual-identity"),
                DeclarationHandle.Create(Owner + "centered_goal_residual_identity"),
                H("Exact signed primal-dual identity"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual aligned eigenvector and a domain trial yield a complex identity with leading correction -inner(v,r). The full projected dual residual and the independent eigenvalue-shift difference are retained. Neither an exact dual solve nor Galerkin orthogonality is assumed."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-centered-goal-residual-bound"),
                DeclarationHandle.Create(Owner + "centered_goal_residual_bound"),
                H("A product remainder around the signed correction"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Cauchy-Schwarz bounds the exact identity by (S+eta*V)*R. S is the complete dual residual norm, not its retained coordinates. This bounds a disk around a signed complex correction, instead of discarding it inside a worst-direction residual norm."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-centered-goal-corrected-ratio-bound"),
                DeclarationHandle.Create(Owner + "centered_goal_corrected_ratio_bound"),
                H("Normalize by the known model origin"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual origin is proved nonzero from the candidate-error and origin margins. Replacing its denominator by the model denominator adds a necessary product term involving the signed defect. The source explicitly retains that term; corrected-output convergence alone would not establish convergence to the original model."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-projective-goal-corrected-ratio-bound"),
                DeclarationHandle.Create(Owner + "projective_goal_corrected_ratio_bound"),
                H("Consume the actual projective Rayleigh enclosure"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The existing owner constructs the aligned eigenvector and gives its norm-error radius. Apply the signed residual and quotient bounds to the actual eigenvector ratios. The scalar defect and complete dual residual remain independently certifiable arithmetic quantities."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-pairing-finite-head-bound"),
                DeclarationHandle.Create(Owner + "model_pairing_finite_head_bound"),
                H("Pay both sides of a truncated scalar pairing"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Split the action into a finite head and an orthogonal tail. Keep the action-tail times model-distance error and the head times polynomial-model error. This is the algebraic adapter for the actual signed model-pairing interval computation."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-tail-sq-from-captured-head"),
                DeclarationHandle.Create(Owner + "model_tail_sq_from_captured_head"),
                H("Use captured unit-model energy for the entire tail"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The exact orthogonal norm decomposition and a head-approximation error give an upper bound on the whole model tail. Subtract the approximation radius before squaring. The interval consumer keeps outward rounding in the nearly cancelling unit-minus-head expression."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-prime-three-goal-correction-budget"),
                DeclarationHandle.Create(Owner + "prime_three_goal_correction_budget"),
                H("Exact arithmetic on independent fixed-window inputs"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Check the old Rayleigh radius, origin margin, transported full dual-residual cap, and new signed-pairing cap. The resulting corrected-output radius is below 885/1000000 and the uncorrected model-ratio error below 891/1000000. This rational implication does not prove the inherited spectral/domain data or the newly evaluated scalar pairing."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-signed-goal-residual-neighborhood"),
                DeclarationHandle.Create(Owner + "signed_goal_residual_neighborhood"),
                H("Full projected dual residual on a frequency neighborhood"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("One trial and one spectral center are fixed. The exact difference of the two complete residuals is the centered-Riesz-vector difference after a contractive projection. A certified variation bound yields S+radius for every point in the set; finite sampling alone supplies no such result."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-sector-projective-signed-ratio-bound"),
                DeclarationHandle.Create(Owner + "sector_projective_signed_ratio_bound"),
                H("Restrict the actual domain before using the stronger gap"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The candidate, genuine model, actual eigenvector and repaired trial all belong to the specified complex submodule. Restrict both domain maps, derive the new model-complement coercivity with the existing positive-form theorem, and apply the existing signed actual-eigenvector ratio theorem. The sector gap is never substituted for a whole-space lower bound. Full Hilbert residual and denominator conditions remain explicit."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-finite-pairing-corrected-ratio-bound"),
                DeclarationHandle.Create(Owner + "finite_pairing_corrected_ratio_bound"),
                H("Pay a finite complex pairing radius"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Translate the corrected-output disk from the exact signed pairing to a computed complex approximation. Its complete error radius is divided by the independently certified model-origin floor. This does not determine the sign of the actual output."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-signed-goal-original-model-uniform-limit"),
                DeclarationHandle.Create(Owner + "signed_goal_original_model_uniform_limit"),
                H("Close the actual eigenmode to the original model limit"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("For varying spaces and operator domains, the theorem consumes actual eigenpairs, model energies, complement coercivity, complete dual residuals, signed-pairing budgets and origin margins. The preceding projective theorem derives the output estimate. Vanishing normalized signed defect and full product remainder, plus convergence of the SAME original model, imply uniform convergence of the actual normalized eigenmode. No desired output-error hypothesis is inserted; the physical arithmetic rates and actual model limit are still independent inputs."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-prime-three-sector-signed-budget"),
                DeclarationHandle.Create(Owner + "prime_three_sector_signed_budget"),
                H("Exact signed-sector certificate synthesis"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The recorded even threshold 1/1000 and positive-form model transport give radius 212/100000 on the restricted even domain. Complete centered-kernel variation extends the same trial to the disk of radius 1/1000. A finite signed-pairing error 6/10^9 is paid. Rational arithmetic gives corrected-output error below 99/10^6 and original-model error below 53/500000. This is a conditional synthesis of previously computed full-sector and model data, not a new spectral computation or an all-scale theorem."))),
                DescribeRole.Theorem))));
}
