                DescribeId.Create("genuine-model-model-centered-normalized-uniform-limit"),
                DeclarationHandle.Create(Owner + "model_centered_normalized_uniform_limit"),
                H("A single centered directional rate on moving domains"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The target set, operators, domains, eigenvectors and readouts may vary with scale. The derived anchor and four-times centered coefficient reduce normalized uniform error to nu*C/b^2 tending to zero. This is not a proof of that arithmetic rate for the actual unbounded Weil/prolate family. The generic readout can use the already-identified Fourier Riesz vector; no new Fourier definition or interval-oracle theorem is introduced."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-repair-preserves-residual-pairing"),
                DeclarationHandle.Create(Owner + "model_repair_preserves_residual_pairing"),
                H("The repaired trial keeps the signed model defect"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Symmetry derives the real Rayleigh pairing. Its full residual is orthogonal to the unit model, so subtracting any multiple of that model leaves the signed pairing unchanged. The original trial action and the complete model still occur; no finite truncation is asserted."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-centered-goal-residual-identity"),
                DeclarationHandle.Create(Owner + "centered_goal_residual_identity"),
                H("Exact signed primal-dual identity"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual aligned eigenvector and a domain trial yield a complex identity with leading correction -inner(v,r). The full projected dual residual and the independent eigenvalue-shift difference are retained. Neither an exact dual solve nor Galerkin orthogonality is assumed."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-centered-goal-residual-bound"),
                DeclarationHandle.Create(Owner + "centered_goal_residual_bound"),
                H("A product remainder around the signed correction"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Cauchy-Schwarz bounds the exact identity by (S+eta*V)*R. S is the complete dual residual norm, not its retained coordinates. This bounds a disk around a signed complex correction, instead of discarding it inside a worst-direction residual norm."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-centered-goal-corrected-ratio-bound"),
                DeclarationHandle.Create(Owner + "centered_goal_corrected_ratio_bound"),
                H("Normalize by the known model origin"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The actual origin is proved nonzero from the candidate-error and origin margins. Replacing its denominator by the model denominator adds a necessary product term involving the signed defect. The source explicitly retains that term; corrected-output convergence alone would not establish convergence to the original model."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-projective-goal-corrected-ratio-bound"),
                DeclarationHandle.Create(Owner + "projective_goal_corrected_ratio_bound"),
                H("Consume the actual projective Rayleigh enclosure"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The existing owner constructs the aligned eigenvector and gives its norm-error radius. Apply the signed residual and quotient bounds to the actual eigenvector ratios. The scalar defect and complete dual residual remain independently certifiable arithmetic quantities."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-pairing-finite-head-bound"),
                DeclarationHandle.Create(Owner + "model_pairing_finite_head_bound"),
                H("Pay both sides of a truncated scalar pairing"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Split the action into a finite head and an orthogonal tail. Keep the action-tail times model-distance error and the head times polynomial-model error. This is the algebraic adapter for the actual signed model-pairing interval computation."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-model-tail-sq-from-captured-head"),
                DeclarationHandle.Create(Owner + "model_tail_sq_from_captured_head"),
                H("Use captured unit-model energy for the entire tail"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("The exact orthogonal norm decomposition and a head-approximation error give an upper bound on the whole model tail. Subtract the approximation radius before squaring. The interval consumer keeps outward rounding in the nearly cancelling unit-minus-head expression."))),
                DescribeRole.Theorem),
            Describe.Lean(
                DescribeId.Create("genuine-model-prime-three-goal-correction-budget"),
                DeclarationHandle.Create(Owner + "prime_three_goal_correction_budget"),
                H("Exact arithmetic on independent fixed-window inputs"),
                StatementSource.FromLean(), AssessedProvenance.FromRepo(),
                Blocks(Paragraph(Text("Check the old Rayleigh radius, origin margin, transported full dual-residual cap, and new signed-pairing cap. The resulting corrected-output radius is below 885/1000000 and the uncorrected model-ratio error below 891/1000000. This rational implication does not prove the inherited spectral/domain data or the newly evaluated scalar pairing."))),
                DescribeRole.Theorem))));
}
